server:
    port: 8081

spring:
    profiles:
        active: dev
    ## notice :two springboot project deploy(部署）in same server
    jmx:
        default-domain: springbootEcharts
    datasource:
        name: test
        #主数据源，默认配置
        url: jdbc:sqlserver://192.168.0.14;DatabaseName=JSDB
        username: ccdbz
        password: ccdbz123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#        url: jdbc:mysql://127.0.0.1/JSDB
#        username: root
#        password: 962464
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
        # 模板模式 LEGACYHTML5
        mode: HTML5
        # 这个开发配置为false，避免改了模板还要重启服务器
        cache: false
        # ######下面的这些可不用配置#######
        # 这个是配置模板路径的，默认就是templates
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        # 检查模板位置
        check-template-location: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zta.efficiency.model

#pagehelper分页插件
pagehelper:
  helperDialect: sqlserver
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      cnepay: trace
